<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-HBCBIO0" ignored="0" name="Test123" tests="7" failures="1" timestamp="04 Jun 2020 14:22:29 GMT" time="0.123" errors="0">
  <testcase name="hardAssert" time="0.02" classname="org.Failed.Testcase1"/>
  <testcase name="test1" time="0.007" classname="org.Failed.Testcase1"/>
  <testcase name="test2" time="0.005" classname="org.Failed.Testcase1">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="org.Failed.Testcase1">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="org.Failed.Testcase1">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.004" classname="org.Failed.Testcase1">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="org.Failed.Testcase1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.Failed.Testcase1.test2(Testcase1.java:16)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test123 -->
